"""
Updated March 18, 2025

This script takes a transient absorption CSV generated by TimeSpec and processes it (background subtraction,
normalization, FFT.))


"""
# %%

from os.path import dirname, join, basename
import sys

# Find code directory relative to our directory to import correct version of pipersfunctions.
THIS_DIR = dirname(__file__)
sys.path.append(THIS_DIR)

import processing_package as pp
import config

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr

if __name__ == "__main__":
    #filepath = select_file()
    relative_path = r"..\TRR\raw_data\2025-08-28\15-flakeskinny-2p0T-300kSF-3p62mV-500ps-1pass-1500msdwell-930probe"
    
    filepath = join(THIS_DIR, relative_path)
    filename = basename(filepath)

    rawData = pd.read_csv(filepath, usecols = [0, 1], sep = r"\s+", header = None)
    
    # Create a data array with time in ps
    dataArray = xr.DataArray(data = rawData[1], coords = {'time': 10**(-3)*rawData[0]}, dims = ['time'])
    pp.plot_data_array(dataArray, title = "%s" % filename)

    # Initial processing of the data, subtracting background and dividing out scale factor and R_0
    background_subtracted_data = pp.subtract_background(dataArray, threshold = -500)
    processed_data = pp.divide_out_factors(background_subtracted_data)

    # Extract time and values
    time_vals = dataArray.coords['time'].values
    y_vals = dataArray.values

    # time_vals, y_vals = pp.mask(time_vals, y_vals, 35, 450) 
    time_vals, y_vals = pp.mask(time_vals, y_vals, 10, 500) 

    plt.plot(time_vals, y_vals)
    plt.title("raw data")
    plt.show()

    t_uniform, y_uniform = pp.uniform_time_grid(time_vals, y_vals, num_points=1000)
    # background_subtracted_data = subtract_exponential_decay(t_uniform, y_uniform, time_constant = 0.01)
    background_subtracted_data = y_uniform - np.average(y_uniform)
    windowed_data = pp.apply_hanning_window(background_subtracted_data)



    plt.plot(t_uniform, background_subtracted_data, label = "No Window")
    plt.plot(t_uniform, windowed_data, label = "Hanning Window")
    plt.title("subtracted data")
    plt.xlabel("Time (ps)")
    plt.legend()
    plt.show()

    # Compute FFT
    freqs, fft_magnitude = pp.compute_fft(t_uniform, background_subtracted_data)
    _, windowed_magnitude = pp.compute_fft(t_uniform, windowed_data)

    freqs_masked, fft_magnitude_masked = pp.mask(freqs, fft_magnitude, 0, 0.2)
    _, windowed_fft_magnitude_masked = pp.mask(freqs, windowed_magnitude, 0, 0.2)

    # Plot positive frequencies
    plt.figure(figsize=(8, 5))
    plt.plot(freqs_masked*1000, fft_magnitude_masked, label = "No Window")
    #plt.plot(freqs_masked*1000, windowed_fft_magnitude_masked, label = "Hanning Window")
    plt.xlabel("Frequency (GHz)")
    plt.ylabel("Magnitude")
    plt.title("FFT")
    plt.legend()
    plt.grid()
    plt.show()

    # Get the most dominant frequencies
    max_indices = np.argpartition(fft_magnitude_masked, -2)[-3:]
    max_frequencies = freqs_masked[max_indices]

    print("Max Frequencies (GHz):", max_frequencies*1000)

#%%